DROP TABLE if exists PERSON;
CREATE TABLE PERSON (
       ID INT NOT NULL AUTO_INCREMENT
     , FIRST_NAME VARCHAR(120) NOT NULL
     , LAST_NAME VARCHAR(120) NOT NULL
     , PATRONYMIC VARCHAR (120)
     , DESCRIPTION VARCHAR(2000)
	 , DEPARTMENT VARCHAR (196)
	 , POSITION VARCHAR (180)
	 , PHOTO BLOB
	 , BIRTH_DATE DATE
     , PRIMARY KEY (ID)
);

DROP TABLE if exists HISTORY;
CREATE TABLE HISTORY (
       ID INT NOT NULL AUTO_INCREMENT
     , PERSON_ID INT NOT NULL
     , REC VARCHAR(2000) NOT NULL
     , WHEN_DATE DATE
     , PRIMARY KEY (ID)
     , CONSTRAINT FK_HISTORY FOREIGN KEY (PERSON_ID) REFERENCES PERSON(ID)
);